spring:
    application:
        name: basics

    datasource:
        url: jdbc:mysql://localhost:3306/basics?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

logging:
    level:
        org:
            springframework:
                security: DEBUG

server:
    ssl:
        key-store: classpath:localhost.p12
        key-store-type: PKCS12
        key-store-password: 123
